apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-gateway-config
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP__modules__api-gateway__config__bind_addr: "0.0.0.0:{{ .Values.service.port }}"
  APP__modules__api-gateway__config__auth_disabled: "{{ .Values.authDisabled }}"
  APP__modules__api-gateway__config__prefix_path: "{{ .Values.gateway.prefixPath }}"
  APP__modules__api-gateway__config__cors_enabled: "{{ .Values.gateway.corsEnabled }}"
  APP__modules__api-gateway__config__enable_docs: "true"
